# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmg_ll_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_pmg_ll_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c)
}

pmg_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_pmg_der_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

pmg_hes_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_pmg_hes_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_ll_eigen <- function(X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_ptmg_ll_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_der_eigen <- function(X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_ptmg_der_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

call_cumsumy <- function(count, fid, k, ng) {
    .Call('_nebula_call_cumsumy', PACKAGE = 'nebula', count, fid, k, ng)
}

call_posindy <- function(count, k, nc) {
    .Call('_nebula_call_posindy', PACKAGE = 'nebula', count, k, nc)
}

center_m <- function(X_c) {
    .Call('_nebula_center_m', PACKAGE = 'nebula', X_c)
}

cv_offset <- function(offset_c, input, nc) {
    .Call('_nebula_cv_offset', PACKAGE = 'nebula', offset_c, input, nc)
}

ptmg_ll_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_ptmg_ll_der_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_ll_der_hes_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call('_nebula_ptmg_ll_der_hes_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

opt_pml <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord) {
    .Call('_nebula_opt_pml', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord)
}

opt_pml_nbm <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord) {
    .Call('_nebula_opt_pml_nbm', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord)
}

pml_ll_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, logw_c, sigma_c) {
    .Call('_nebula_pml_ll_der_eigen', PACKAGE = 'nebula', X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, logw_c, sigma_c)
}

